### ISSUE TITLE
Se reparo un error al entregar medallas que ocasionaba un fallo al registrarla en la BD

### ISSUE THREAD

**Issue by Zixtor195** [MCV-Univalle/Freiya#286]

**Comment by edwingamboa** [comment]
Se entregan mas insignias de las debidas![WhatsApp Image 2020-02-13 at 21.32.56.jpeg](https://images.zenhubusercontent.com/5a859ccc4b5806bc2bc70f1c/9a5b20db-e605-42bb-9ef1-2d76fdb8643b)![WhatsApp Image 2020-02-13 at 21.33.01.jpeg](https://images.zenhubusercontent.com/5a859ccc4b5806bc2bc70f1c/78df0a9e-c255-4db1-bc15-4ecdba5e623c)
