### ISSUE TITLE
Modificación del modo Juego en la actividad de preguntas

### ISSUE THREAD

**Issue by Zixtor195** [MCV-Univalle/Freiya#289]
se realiza una función que genera un numero de rondas de forma pseudo-aletoria la cual va siguiendo el orden de los estudiantes, disminuyendo el tiempo que vibran y suenan los dispositivos, esto con el objetivo de dar la sensación de aumento de velocidad

**Comment by edwingamboa** [comment]
Evidencia de cumplimiento, imagen, video?

**Comment by edwingamboa** [comment]
En el modo al azar:

- [ ] A veces el celualr no deja de sonar

- [ ] Debería haber una diferencia entre el sonido de cuando rota (Tingo), y cuando se elige (Tango)
